# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cQ2718xmKhQOMmyNZYeu0guoJDdHyszawS4wqfkbMapc+bHs0pHmQNQNAvwt2+d9wIj1LfU3Xl7v4kDIoCC6bEW1/eb2Obvtm1YnxMENOv6pkCH/wjYnGJP5Pzb05+qQHT/BJE9Tu/RscB3hWxY+Uj/n02ZCW86LveRDOxSjGzZxYDAvkMJ5RVVZXgOli2Pefr1hJiC77Gd8Ymegyh68GdZ0+r3TKL0Mbng+2HwQCRlTv4yo9fTrF2lcpAUs3fNz6BmuivpbPZfqtEiNN5L9gFLcgOyIr9PgFrN+fkLS2bR0A3LKL/UPmnYl/yrdHPvgPFPP3gwRWEPL/5favNyTWaENZ5u5XXN9wRnArMD7N8Lk59+K1YOqugqWKPg6R0I4OOMMxYc0hrNn4rx/BqU2dmn1Fm8CjW3L1T05t2wIR9lDGokjwbxnskxtADDyT5Jm1BIgU9B56ZSl/zUb9gKOAJi24NEXPh1F/7E9o65egDpqnHXmZ3GIl7TFQJ38LnLUkx/T6D798ztyLUBEXlkxQJWYX+4Px2oBabZxrIqfu/3vqGKIl1SIEoBBYBLSlo1siGZlHOEIYcUcOCbh3m8g4VhkXehgtjBK51DvySYQL6lsJ80gklvn+8wduTt2L67QrzA6+hU0hEaD5+/tLEoQEp4JOIrTmn3Qp15pikwc6ow="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
