travis:
  secure:
    BINSTAR_TOKEN: cQ2718xmKhQOMmyNZYeu0guoJDdHyszawS4wqfkbMapc+bHs0pHmQNQNAvwt2+d9wIj1LfU3Xl7v4kDIoCC6bEW1/eb2Obvtm1YnxMENOv6pkCH/wjYnGJP5Pzb05+qQHT/BJE9Tu/RscB3hWxY+Uj/n02ZCW86LveRDOxSjGzZxYDAvkMJ5RVVZXgOli2Pefr1hJiC77Gd8Ymegyh68GdZ0+r3TKL0Mbng+2HwQCRlTv4yo9fTrF2lcpAUs3fNz6BmuivpbPZfqtEiNN5L9gFLcgOyIr9PgFrN+fkLS2bR0A3LKL/UPmnYl/yrdHPvgPFPP3gwRWEPL/5favNyTWaENZ5u5XXN9wRnArMD7N8Lk59+K1YOqugqWKPg6R0I4OOMMxYc0hrNn4rx/BqU2dmn1Fm8CjW3L1T05t2wIR9lDGokjwbxnskxtADDyT5Jm1BIgU9B56ZSl/zUb9gKOAJi24NEXPh1F/7E9o65egDpqnHXmZ3GIl7TFQJ38LnLUkx/T6D798ztyLUBEXlkxQJWYX+4Px2oBabZxrIqfu/3vqGKIl1SIEoBBYBLSlo1siGZlHOEIYcUcOCbh3m8g4VhkXehgtjBK51DvySYQL6lsJ80gklvn+8wduTt2L67QrzA6+hU0hEaD5+/tLEoQEp4JOIrTmn3Qp15pikwc6ow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
