travis:
  secure:
    BINSTAR_TOKEN: hicvlNpAbrSk6Wkz9n3klfDb3IQoCrs4ubsmZC5xehvFHYNYWXGw9udAn2gTDtiq3QiVuTTmQPAtX5amYq97Xom1WeDp9hlaMFwotzrntrPelBPjUnhbEsWK0JOpX9aO7Xlb0YR3ex2n8SAC+Pd40qaX1q7+MJY8ZL/OomMXwAy8ABI6HhF7+hZiff8EqKPPCUcszwClTzTRWkZKLARcBBiGR3wBTxmO81rf2G18MZupCj0Rr4sFyl9oql94djx5H1/MGuAZnx59vtwKkgNHmPXExej6ZZFVwVvdqMiS/76Tgcjz2b1t11lvx64nSjxYv2Yosg98CL5jD5Fz6e1cUB0xRVcnQsrz6lmOPE6GZCqMtV2eigPJyhLoaaTtfK6WPiL+vzrIxAGlWqcupDJRwOj3nJoVMjPpsZuP0dXK8inkrABDCfHsqDGX406WrpnIyYx48P1OJoeDDpkbRC/DvUr+Kd4iWp5yMEi6/FdUsMhEKb/ozA08baxvc5TXcIxm/u4X0e4ydOst+atkpzASCOe/xk0kGHSt+bU6cwZjQpkaUHphJT+ptM2F00C5zcCH3VS6hkXm2nhssLQC1P6xOTBhZyWVJqc95lTkuUCoGdTb8UWkM+dAjMYYqF7fR2QPxvhH6qB+4MnPBr3ONxk22BHdQkqAJt8ChSgkp6+udmg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
