appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RmIRlMPorW3rasGPO1Tte8DGz78C9TFmugVoXL65etVqMt6x/TgAPuJTo5xpXtxcBBc30GjjnFsLTceeXtJkkEHcqvaNItzBzNCvrouDCCQYnTPiYGXSZEqZGSsHPsys/XajwqNhgu4ZkbjpnrVbPZt5ML33Sbx/lifJn28p0VIZx9ImUozriqQ1yLBfPiaVeaSC8qNonIDb/ymzAo89qaeUmwNo8XL0OPyA9fzkmc++NxBTUJVSlrRIilFEmMjt5VMrOONBHQJ+3BdhYCf4U5Jor9Q1WX1/cD5N6mzGSjAXrCSitozEWEIRkqlVbnCKfYUDsUWHRIIynayckXRdRre0L0XfwVOzuiCwJSDjsTdqkMna3TtRfZv/nehBydOY2k3UEqmTd9cjm8rDfHsn4+rcpv33GUuljZjIs9/sWwUe0qxpjBAs4EfF4MjpGGVmTXK8VEdabT0TEbG9CRxYRSqXsjY5g1UJUyDp8nW//i1ajtN88zNmCHJL/pFhLhBdFhKROqaGJquw1M/zXbpXEAhGvAjafQWC3sToejMw7ZuA2YWXMDd8EphAx4l/9vVFWwHvzJaT273fBnTyqNFyTuJXQlXtW/p4+sV2tzTcrwLjuFoThMaarkIvlzfe34MtqQZ+yDshD1I/VkZIGig7fSeYH3A74AnUoNVMZ7qjv44=}
